route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'telegram'

receivers:
- name: 'telegram'
  webhook_configs:
  - send_resolved: true
    url: 'https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage?chat_id=******'
    http_config:
      bearer_token: '************'
