version: '3.3'
services:
    jenkins:
        image: jenkins    
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes:
            - './jenkins:/var/jenkins_home'
