version: '3'

services:
  master-postgres:
    image: postgres:15
    container_name: master-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: abc_123
      POSTGRES_DB: db_teste1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./pgpool-config/pool_passwd.conf:/opt/pgpool/pool_passwd.conf
      #- ./pgpool-config/replica_pool_passwd.sh:/var/lib/postgresql/replica_pool_passwd.sh
      - type: bind
        source: ./postgres15/master_data
        target: /var/lib/postgresql/data    
    networks:
      - db-network
    command: postgres -c max_wal_senders=3 -c wal_level=replica
    #command: ["/var/lib/postgresql/replica_pool_passwd.sh"]

  slave-postgres:
    image: postgres:15
    container_name: slave-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc_123
      POSTGRES_DB: db_teste1
      POSTGRES_MASTER_HOST: master-postgres
      POSTGRES_MASTER_PORT: 5432
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ./postgres15/slave_data
        target: /var/lib/postgresql/data
    networks:
      - db-network
    depends_on:
      - master-postgres
    command: postgres -c max_wal_senders=3 -c wal_level=replica -c hot_standby=on

  pgpool2:
    image: pgpool/pgpool
    container_name: pgpool2
    ports:
      - "9999:9999"
    environment:
      PGPOOL_BACKENDS: "0:master-postgres:5432:1 1:slave-postgres:5432:1"
      PGPOOL_PARAMS_BACKEND_HOSTNAME0: "master-postgres"
      PGPOOL_PARAMS_BACKEND_PORT0: "5432"
      PGPOOL_PARAMS_BACKEND_HOSTNAME1: "slave-postgres"
      PGPOOL_PARAMS_BACKEND_PORT1: "5432"
      PGPOOL_PCP_USER: "pgpool"
      PGPOOL_PCP_PASSWORD: "abc-123"
      PGPOOL_SR_CHECK_USER: "pgpool"
      PGPOOL_SR_CHECK_PASSWORD: "pgpool_2"
      PGPOOL_ENABLE_LDAP: "no"
      PGPOOL_POSTGRES_USERNAME: "postgres"
      PGPOOL_POSTGRES_PASSWORD: "abc_123"
      PGPOOL_ADMIN_USERNAME: "admin"
      PGPOOL_ADMIN_PASSWORD: "apl_783"
      PGPOOL_ENABLE_LOAD_BALANCING: "yes"
      PGPOOL_ENABLE_POOL_HBA: "no"
      PGPOOL_USER_HBA_FILE: "/etc/pgpool2/pg_hba.conf"
      PGPOOL_ENABLE_POOL_PASSWD: "yes"
      PGPOOL_PASSWD_FILE: "/etc/pgpool2/pool_passwd.conf"
      PGPOOL_NUM_INIT_CHILDREN: 100
      PGPOOL_MAX_POOL: 1
      PGPOOL_CLIENT_IDLE_LIMIT: 600
      PGPOOL_CHILD_LIFE_TIME: 0
      PGPOOL_ENABLE_LOG_PER_NODE_STATEMENT: "yes"
      PGPOOL_ENABLE_LOG_CONNECTIONS: "yes"
      PGPOOL_ENABLE_LOG_HOSTNAME: "yes"
      PGPOOL_AUTO_FAILBACK: "no"
    volumes:
      - ./pgpool-config:/etc/pgpool2
    networks:
      - db-network
    command: ["pgpool", "-n", "-a", "/etc/pgpool2/pgpool.conf"]


volumes:
  master-data:
  slave-data:
  pgpool-config:

networks:
  db-network:
