version: '3.9'

services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    cpus: '1.0'
    mem_limit: '1024m'
    dns:
      - 1.1.1.1
    volumes:
      - ./config_prometheus:/etc/prometheus
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: always  
    networks:
      - observabilidade

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.23.0
    cpus: '1.0'
    mem_limit: '1024m'    
    volumes:
      - "./alertmanager:/config"
      - "./alertmanager-data:/data"
    command: --config.file=/config/alertmanager.yml --log.level=debug
    ports:
      - "9093:9093"
    networks:
      - observabilidade

  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    container_name: blackbox_exporter
    cpus: '1.0'
    mem_limit: '1024m'    
    dns:
      - 1.1.1.1 
    volumes:
      - ./black_box/config:/etc/blackbox
    command:
      - --config.file=/etc/blackbox/blackbox.yml
    ports:
      - "9115:9115"
    networks:
      - observabilidade
  
  grafana:
    container_name: grafana
    image: grafana/grafana
    cpus: '1.0'
    mem_limit: '1024m'    
    volumes:
      - ./grafana/data:/var/lib/grafana
    env_file:
      - ./grafana/data/grafana.config
    ports:
      - 3000:3000
    networks:
      - observabilidade

networks:
  observabilidade:

  # Descomente e ajuste as configurações para o nodeexporter se necessário
  #nodeexporter:
  #  image: prom/node-exporter:latest
  #  container_name: nodeexporter
  #  user: root
  #  privileged: true
  #  volumes:
  #    - ./nodeexporter/proc:/host/proc:ro
  #    - ./nodeexporter/sys:/host/sys:ro
  #    - ./nodeexporter/:/rootfs:ro
  #  command:
  #    - '--path.procfs=/host/proc'
  #    - '--path.sysfs=/host/sys'
  #    - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
  #  restart: unless-stopped
  #  expose:
  #    - 9100
  #  ports:
  #    - "9100:9100"
  #  networks:
  #    - observabilidade  
